apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pitc-ansible-training-prod-github-deployment
  namespace: pitc-ansible-training-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pitc-ansible-training-prod-github-deployment
