name: PRCleanup Slides Test
on:
  pull_request:
    types: [closed]
    paths:
      - 'slides/**'

jobs:
  delete-slides-test:
    runs-on: 'ubuntu-latest'
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - 
        name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.21.2
      - 
        name: Create KUBECONFIG
        env:
          KUBE_CONFIG: '${{ secrets.KUBECONFIG_TEST }}'
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config

      - name: Delete Tags on Quay
        id: delete_tags
        env:
          QUAYIO_API_TOKEN: '${{ secrets.QUAYIO_API_TOKEN }}'
        run: |
          curl -X DELETE -H "Authorization: Bearer ${QUAYIO_API_TOKEN}" https://quay.io/api/v1/repository/puzzle/ansible-training/tag/test
